[package]
name = "ftp-fighter"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "server", "api"]

[dependencies]
# cli parsing
clap = "4.0.7"
# ftp lib
libunftp = "0.18.5"
# own implementations
unftp-filefighter = { path = "./server" }
# async
tokio = { version = "1", features = ["full"] }
# logging and log panics better
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
color-eyre = "0.6.2"
