[package]
name = "ftp_fighter"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "auth", "server", "api"]

[dependencies]
libunftp = "0.18.5"
tokio = { version = "1", features = ["full"] }
# own implementations
unftp-sbe-filefighter = { path = "./server" }
unftp-auth-filefighter = { path = "./auth" }
tracing-subscriber = "0.3.15"
tracing = "0.1.36"
