[package]
name = "ftp-fighter"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "server", "api"]

[dependencies]
libunftp = "0.18.5"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
color-eyre = "0.6.2"
# own implementations
unftp-filefighter = { path = "./server" }
