[package]
name = "unftp-auth-filefighter"
version = "0.1.0"
edition = "2021"


[dependencies]
async-trait = "0.1.56"
libunftp = "0.18.5"
tracing = "0.1.36"
filefighter-api = { path = "../api" }
url = "2.3.1"
