[package]
name = "unftp-sbe-filefighter"
version = "0.1.0"
edition = "2021"


[dependencies]
async-trait = "0.1.56"
libunftp = "0.18.5"
tokio = "1.21.1"
tracing = "0.1.36"
# own auth
unftp-auth-filefighter = { path = "../auth" }
