[package]
name = "filefighter-api"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
