[package]
name = "filefighter-api"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.12", features = ["json", "cookies","multipart","stream"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
sha256 = "1.0.3"
thiserror = "1.0.35"
tracing = "0.1.36"
tokio = "1.21.1"
tokio-stream = "0.1.10"
futures = "0.3"
tokio-util = { version = "0.6.9", features = ["compat","io"] }
new_mime_guess = "4.0.1"
