name: Latest Release

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  Build_Docker_Image_on_Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run Checks and Test
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-features -- -D warnings
          cargo test --all
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PW }}
      - name: Build and Push Image
        run: |
          docker build . -t filefighter/ftp-service:latest
          docker push filefighter/ftp-service:latest
